### ISSUE TITLE
CUSA03365 - DARK SOULS™ III

### ISSUE THREAD

**Issue by bigol83** [shadps4-compatibility/shadps4-game-compatibility#1651]
### Checklist

- [x] I've tested on the [latest major release](https://github.com/shadps4-emu/shadPS4/releases/latest) and not on a nightly build (In this case 0.11.0 and NOT 0.11.1 WIP).
- [x] My report is made on an officially released PlayStation 4 game. (You can find a list of official PlayStation 4 games [here](https://www.serialstation.com/games/?systems=97ec53a2-f676-4c89-8172-e653dce5eed1))
- [x] I've made sure there are no other issues opened for this game and operating system combo.
- [x] My game dump comes from a copy of the game I own.
- [x] My game dump is unmodified, I haven't enabled any game patches and I didn't repackage my game dump to a FPKG.
- [x] I've dumped my PlayStation 4's firmware libraries, and placed all that the [compatibility list description](https://github.com/shadps4-compatibility/shadps4-game-compatibility?tab=readme-ov-file#information) mentions in the shadPS4 'sys_modules' folder.
- [x] I've made sure my logging type is set to "sync" and not "async".
- [x] I did not manually enable any settings that would change emulation behavior (such as "isPS4Pro", "isDevKit", "Vblank Divider" etc).

### Game Name

DARK SOULS™ III

### Game serial

CUSA03365

### Game version

01.15

### Used emulator's version (only major released versions are acceptable)

0.11.0

### Current status

Ingame

### Operating System

Windows

### Error

The game reaches ingame but crashes after few seconds with

```
[Debug] <Critical> video_out.cpp:350 operator(): Assertion Failed!
Out of order flip IRQ
```

### Description

The game looks great, generally there are no graphics issues, sometimes there are vertex explosions like the ones in Bloodborne.

### Screenshots

<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/86450dcf-4274-420c-8e6b-c4f35fcac489" />

### Log File

[CUSA03365.log](https://github.com/user-attachments/files/22402294/CUSA03365.log)

**Comment by kalaposfos13** [comment]
Do vertex explosions get fixed with readbacks?

**Comment by bigol83** [comment]
> Do vertex explosions get fixed with readbacks?

will check and report later

**Comment by bigol83** [comment]
With 0.13.0 it crashes with 

```
[Debug] <Critical> buffer.cpp:90 operator(): Assertion Failed!
Failed allocating buffer with error ErrorOutOfDeviceMemory
```

when it consumes all vram

or

```
[Debug] <Critical> video_out.cpp:350 operator(): Assertion Failed!
Out of order flip IRQ
```

[CUSA03365.log](https://github.com/user-attachments/files/24328506/CUSA03365.log)

<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/78efc7ba-58ec-457f-95e7-e5e6591335f0" />
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/28da3edf-b047-40e1-a432-53f5a9ebe5dc" />

there is some missing graphics depending on camera angle, like in the second image where the fire is floating

**Comment by Missake212** [comment]
Still crashes on Out of order flip IRQ after a few minutes on 0.15.0.

[CUSA03365.log](https://github.com/user-attachments/files/26863545/CUSA03365.log)

**Comment by Missake212** [comment]
On 0.16.0, the keyboard now shows up when creating a new character, also performance isn't stable 30 FPS but that was also the case on 0.15.0, no changes other than that.

<img width="1924" height="1134" alt="Image" src="https://github.com/user-attachments/assets/2cc5c5cf-3cf9-410e-b02e-0b0bac18b4c7" />

[CUSA03365.log](https://github.com/user-attachments/files/28473802/CUSA03365.log)
