### ISSUE TITLE
CUSA12549 - Just Dance® 2019

### ISSUE THREAD

**Issue by Missake212** [shadps4-compatibility/shadps4-game-compatibility#23]
### Game Name

Just Dance® 2019

### Game code

CUSA12549

### Game version

v01.04

### Used emulator's version (only major released versions are acceptable)

v0.6.0

### Current status

Boots

### Operating System

Windows

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900cd2352
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelIsStack (nid: yDBwVAolDgg) called, returning zero to 0x900771628
[Core] <Error> stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900cd2352
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelIsStack (nid: yDBwVAolDgg) called, returning zero to 0x900771628
[Core] <Error> stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900cd2352
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceKernelIsStack (nid: yDBwVAolDgg) called, returning zero to 0x900771628

### Description

Boots but hangs indefinitely on the loading screen.

### Screenshots

![Image](https://github.com/user-attachments/assets/9ba69df2-30f9-42aa-9353-fb4cb1288445)

### Log File

[shad_log.zip](https://github.com/user-attachments/files/19233691/shad_log.zip)

**Comment by Missake212** [comment]
No changes on 0.7.0 for Just Dance 2019.

[CUSA12549.zip](https://github.com/user-attachments/files/19406321/CUSA12549.zip)

**Comment by Missake212** [comment]
No changes on 0.8.0 for Just Dance 2019.

[CUSA12549.zip](https://github.com/user-attachments/files/19867189/CUSA12549.zip)

**Comment by Missake212** [comment]
Doesn't hang anymore, just crashes silently on 0.9.0.

[CUSA12549.log](https://github.com/user-attachments/files/20398790/CUSA12549.log)

**Comment by Missake212** [comment]
Now crashes on a device lost on 0.10.0.

[CUSA12549.zip](https://github.com/user-attachments/files/21109762/CUSA12549.zip)

**Comment by Missake212** [comment]
No changes on 0.11.0.

[CUSA12549.log](https://github.com/user-attachments/files/22402717/CUSA12549.log)

**Comment by soopermodel** [comment]
just as an info: just dance on ps4 uses webms with matroska and wave audio files. it also needs to access local network to scan for the smartphone controller.

**Comment by Missake212** [comment]
Gets to the main menu on 0.15.0, the game froze once I clicked the PS Move option (I don't own a PS Move nor a PS Camera so maybe that's why it crashed, it didn't let me pick the PS Camera option on the menu).

<img width="1924" height="1134" alt="Image" src="https://github.com/user-attachments/assets/f2f4e224-f81b-442e-b740-e7295beb19e0" />

<img width="1924" height="1134" alt="Image" src="https://github.com/user-attachments/assets/e8266786-7f70-431f-901f-7b2250f68313" />

[CUSA12549.log](https://github.com/user-attachments/files/26727524/CUSA12549.log)

I then chose to try the mobile device option and I managed to actually properly play the game, I had to install it on my phone, make sure it's connected to the same wifi and then I was able to use my phone to navigate the game in the emulator, I picked a song and danced to it (got a pretty good score too I believe) and I created a profile afterwards, I think that warrants an in game/playable status, unfortunately like I said I'm not able to test the PS Camera or the PS Move (I don't even know if shadPS4 has a way to emulate the PS move or not) so maybe someone else can test it to see if that works.

<img width="1924" height="1134" alt="Image" src="https://github.com/user-attachments/assets/f06bb53a-d09c-45f8-b702-1b7347d5570c" />
<img width="1924" height="1134" alt="Image" src="https://github.com/user-attachments/assets/41c7c684-90e4-4058-9ef2-06574042903f" />
<img width="1924" height="1134" alt="Image" src="https://github.com/user-attachments/assets/0b42bff8-58ad-41b1-9146-c199a1489324" />
<img width="1924" height="1134" alt="Image" src="https://github.com/user-attachments/assets/52e2a813-4120-4564-b237-1aaa6b7890e4" />

[CUSA12549.log](https://github.com/user-attachments/files/26727769/CUSA12549.log)

**Comment by georgemoralis** [comment]
> [@StevenMiller123](https://github.com/StevenMiller123) You forgot the milestone 😅😅

Done! Nice to see you again missake

**Comment by Missake212** [comment]
Nice to see you too shadow, I'm not sure Stephen will be happy that we're having a chat here though 😁

**Comment by StevenMiller123** [comment]
Oops, good catch 😅

**Comment by Missake212** [comment]
On 0.16.0 selecting PS Move still freezes the emulator (the ``issues: crashes`` label should be changed to ``issues: hang``. It still gets in game when paired with a phone.

[CUSA12549PSMove.log](https://github.com/user-attachments/files/28513692/CUSA12549.log)

[CUSA12549.log](https://github.com/user-attachments/files/28513866/CUSA12549.log)

**Comment by seankiel81715-gif** [comment]
Where can I get the ROM? Thank you!
