### ISSUE TITLE
CUSA04518 - Hatsune Miku: Project DIVA X

### ISSUE THREAD

**Issue by StevenMiller123** [shadps4-compatibility/shadps4-game-compatibility#44]
### Game Name

Hatsune Miku: Project DIVA X

### Game serial

CUSA04518

### Game version

v01.02

### Used emulator's version (only major released versions are acceptable)

v0.6.0

### Current status

Boots

### Operating System

Windows

### Description

Boots, but then crashes before the intro cutscene without any critical errors.

### Screenshots

![Image](https://github.com/user-attachments/assets/61a1f85f-237c-4041-8c1d-2aec9dc96dfd)

### Log File

[shad_log.txt](https://github.com/user-attachments/files/19239612/shad_log.txt)

**Comment by StevenMiller123** [comment]
Reaches ingame, though audio is missing, there are some graphical artifacts, and hair physics occasionally break.
![Image](https://github.com/user-attachments/assets/cbc874e0-fab1-493d-8f42-7d48da5aedfe)

![Image](https://github.com/user-attachments/assets/74eed69c-bf07-417c-a163-e5aca3b8882e)

![Image](https://github.com/user-attachments/assets/784e1f6a-95bf-447f-b273-e81e84aafc58)

[shad_log.txt](https://github.com/user-attachments/files/19414168/shad_log.txt)

**Comment by Natriss** [comment]
For me I still can't get into the game. I have the same result as 0.6.0

[shad_log.txt](https://github.com/user-attachments/files/19475288/shad_log.txt)

[\[Lib.Move\] Error move.cpp12 sceMove.txt](https://github.com/user-attachments/files/19475290/Lib.Move.Error.move.cpp12.sceMove.txt)

**Comment by StevenMiller123** [comment]
@Natriss Your report is invalid, as you haven't dumped your PS4's firmware libraries, your logging type is on async, and your game dump appears to be modified or invalid.
If you need assistance fixing these problems, please ask in the shadPS4 Discord server.

If you can replicate these issues after resolving these issues, please send a new report here.

**Comment by Natriss** [comment]
@StevenMiller123 Sorry for the late reply.
I've done it all and I do have the exact same result as you. So I'm not gonna provide a full report here since it's identical.

**Comment by ghost** [comment]
With verison 0.8 it has sound now but it crashes a lot. I can't get past the game's intro.

**Comment by StevenMiller123** [comment]
@Natriss Please share a log if you'd like to make a report.

**Comment by ghost** [comment]
@StevenMiller123 
[shad_log.txt](https://github.com/user-attachments/files/20023386/shad_log.txt)

**Comment by kalaposfos13** [comment]
@Natriss Sorry for the late response, but your log is on async instead of sync, and is also a bad or modified dump, so it is not valid. Please redump the game, and send a new log with the setting corrected. If you need help with this, please visit the [shadPS4 Discord server](https://discord.gg/bFJxfftGW6).

**Comment by ghost** [comment]
@kalaposfos13 Sorry for the late response.

I put it on sync.
It didn't create a .yaml file of the crash diagnostics.
[shad_log_crash.txt](https://github.com/user-attachments/files/20206374/shad_log_crash.txt)
[shad_log_working.txt](https://github.com/user-attachments/files/20206375/shad_log_working.txt)
It's a 50% change with me if it will work or not.

If it is running, there are no crashes during gameplay (at least for me), the audio plays fine, I'm not really seeing graphical glitches.
Sometimes a button doesn't get registered on time, but that only happens occasionally.

**Comment by kalaposfos13** [comment]
@Natriss this is still a repackaged dump, so we cannot accept it until you redump it.

**Comment by StevenMiller123** [comment]
While testing on v0.8.0, I got a random crash while listening to intros

The game was fairly stable beyond that, and audio works perfectly in this release. The graphics issues I reported on before are still present.
![Image](https://github.com/user-attachments/assets/176636bc-1f73-430a-bc07-b441a1701720)

[CUSA04518 crash.log](https://github.com/user-attachments/files/20351482/CUSA04518.crash.log)
[CUSA04518.log](https://github.com/user-attachments/files/20351481/CUSA04518.log)

**Comment by StevenMiller123** [comment]
No difference in v0.9.0

[CUSA04518.log](https://github.com/user-attachments/files/20402822/CUSA04518.log)
[CUSA04518 crash.log](https://github.com/user-attachments/files/20402821/CUSA04518.crash.log)

**Comment by KaylaD23** [comment]
I found with this game that it crashes on launch alot and deleting the opening video seems to atleast make it get to main menu this is same issue ive had with the game on the vita3k emulator where deleting opening vid stops it from crashing its weird issue but yeah thats what fixed it for me atleast.

**Comment by StevenMiller123** [comment]
Game status is mostly unchanged on v0.10.0.

v1.00 of the game crashes on startup.

[CUSA04518 v1.00.log](https://github.com/user-attachments/files/21129484/CUSA04518.v1.00.log)

v1.02 still works, but my current testing setup has a slower CPU (i5-9600K), and that seems to cause extreme performance issues.

[CUSA04518 v1.02.log](https://github.com/user-attachments/files/21129485/CUSA04518.v1.02.log)

**Comment by StevenMiller123** [comment]
Severe performance regression on v0.12.0 (probably specific to AMD RDNA3 based on some other similar regressions), and a shadow rendering issue has cropped up too.
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/98815b72-a2a0-4fae-b9c3-899159f66ac6" />

<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/eb66cd62-867e-4090-808f-2f66cabed3cb" />

[CUSA04518.log](https://github.com/user-attachments/files/23321987/CUSA04518.log)

**Comment by Mranonsys** [comment]
There was a build that fixed the Gamma issue on the US version (and in gravity rush?) but I lost it.

**Comment by StevenMiller123** [comment]
I can't reproduce the shadow issues on v0.12.5, and performance is a tad better, though the game is still prone to significant hitching while spamming `[Render.Vulkan] <Info> vk_pipeline_cache.cpp:284 GetGraphicsPipeline: Compiling graphics pipeline` messages in the log.

[CUSA04518.log](https://github.com/user-attachments/files/23433281/CUSA04518.log)

<img width="1281" height="752" alt="Image" src="https://github.com/user-attachments/assets/c7d1bdad-9974-4374-8c7b-c81bd167695d" />

<img width="1281" height="752" alt="Image" src="https://github.com/user-attachments/assets/488e43ae-e947-49f8-9936-ae2d55ab40b1" />

<img width="1281" height="752" alt="Image" src="https://github.com/user-attachments/assets/26e122b3-70c4-404c-9535-a5a87291a8ba" />

<img width="1281" height="752" alt="Image" src="https://github.com/user-attachments/assets/5dadee47-6a17-44c1-b505-7a4f2b2dff31" />

**Comment by StevenMiller123** [comment]
v0.12.0 performance regression is fully resolved in v0.13.0, though I've yet to check the older performance issues.

<img width="1284" height="767" alt="Image" src="https://github.com/user-attachments/assets/757a00d3-3911-4a12-b8dd-9e06824056f2" />

<img width="1284" height="767" alt="Image" src="https://github.com/user-attachments/assets/57e125f5-d466-479b-b8d1-b73e8b45a005" />

[CUSA04518.log](https://github.com/user-attachments/files/24332526/CUSA04518.log)

**Comment by StevenMiller123** [comment]
No change.

[CUSA04518.log](https://github.com/user-attachments/files/26098463/CUSA04518.log)

**Comment by oheheda** [comment]
Game crash after title screen. I tried shadPS4 version v0.11.0, v0.12.0, v0.125., v0.16.0.

<img width="1924" height="1127" alt="Image" src="https://github.com/user-attachments/assets/19b27ec0-6cc7-4cb9-be6c-6662a9215af6" />

[shad_log.txt](https://github.com/user-attachments/files/29943642/shad_log.txt)

**Comment by Anon10002000** [comment]
ReadbackLinearImages no longer fixes dark graphics in versions above 0.10.1

**Comment by SKingBlue** [comment]
The game still crashes for me on the newest build after the Crypton logo fades. Before the latest Nvidia driver and on 0.16 I could get it past the opening fmv, which wouldn't load it would just play the audio, but then it'd hang on the white screen mentioned before

[shad_log.txt](https://github.com/user-attachments/files/31199446/shad_log.txt)
